services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: smarthome-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Hello123@"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
      - ./backend/Creat_DB_and_Table.sql:/scripts/Creat_DB_and_Table.sql:ro

volumes:
  sqlserver-data:
